# Generated by Django 5.2.2 on 2025-06-10 19:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_alter_offer_min_price_alter_offerdetail_price'),
        ('orders_app', '0002_orderget_orderpost_delete_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPost',
            new_name='OrderMainModel',
        ),
    ]
