# Generated by Django 5.2.2 on 2025-06-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_rename_orderpost_ordermainmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderGet',
        ),
    ]
