# Generated by Django 5.2.2 on 2025-06-09 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_rename_url_offerdetail_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('description', models.TextField()),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_delivery_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers_app.offer')),
            ],
        ),
    ]
