# Generated by Django 5.2.2 on 2025-06-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_offerget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferGet',
        ),
    ]
