# Generated by Django 5.2.2 on 2025-06-13 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0002_rename_reviewgetpostmodel_reviewgetmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewpostmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reviewpostmodel',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewpostmodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reviewpostmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='reviewpostmodel',
            name='business_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_reviews', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewpostmodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewpostmodel',
            name='rating',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
