# Generated by Django 5.2.2 on 2025-06-13 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0003_remove_reviewpostmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpostmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewpostmodel',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
