# Generated by Django 5.2.2 on 2025-06-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0005_reviewpostmodel_created_at_reviewpostmodel_reviewer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPatchDeleteModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reviews_app.reviewpostmodel',),
        ),
    ]
